"""
Project Stonks
Snapshot Writer

Sprint 30A

Purpose
-------
Creates an immutable research snapshot for every recommendation generated by
Project Stonks.

The snapshot represents historical truth and must NEVER be modified after it
has been written.

Responsibilities
----------------
- Generate a Recommendation ID
- Build an immutable research snapshot
- Persist the snapshot to disk as JSON
- Return snapshot metadata to the caller

This module intentionally contains no business logic. It does not determine
what a recommendation should be—it simply preserves it.
"""

from __future__ import annotations

import json
import uuid
from dataclasses import asdict, is_dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


SCHEMA_VERSION = "1.0"
MODEL_VERSION = "0.3.0-alpha"

SNAPSHOT_DIRECTORY = (
    Path(__file__).resolve().parent.parent
    / "data"
    / "history"
    / "recommendations"
)


def _serialize(value: Any):
    """
    Recursively converts objects into JSON-safe values.
    """

    if is_dataclass(value):
        return _serialize(asdict(value))

    if isinstance(value, dict):
        return {
            str(k): _serialize(v)
            for k, v in value.items()
        }

    if isinstance(value, (list, tuple)):
        return [_serialize(v) for v in value]

    if hasattr(value, "__dict__"):
        return _serialize(vars(value))

    if isinstance(value, (datetime,)):
        return value.isoformat()

    return value


def write_snapshot(trade, research_row):
    """
    Writes an immutable research snapshot.

    Parameters
    ----------
    trade
        TradeRecommendation object.

    research_row
        Original research row used to generate the recommendation.

    Returns
    -------
    dict

    {
        "recommendation_id": "...",
        "file_path": "...",
        "created_utc": "...",
        "schema_version": "1.0"
    }
    """

    recommendation_id = str(uuid.uuid4())

    created_utc = datetime.now(timezone.utc)

    SNAPSHOT_DIRECTORY.mkdir(
        parents=True,
        exist_ok=True,
    )

    timestamp = created_utc.strftime("%Y%m%d_%H%M%S")

    ticker = getattr(trade, "ticker", "UNKNOWN")

    filename = (
        f"{timestamp}_{ticker}_{recommendation_id}.json"
    )

    file_path = SNAPSHOT_DIRECTORY / filename

    snapshot = {
        "schema_version": SCHEMA_VERSION,
        "model_version": MODEL_VERSION,
        "recommendation_id": recommendation_id,
        "created_utc": created_utc.isoformat(),
        "trade": _serialize(trade),
        "research": _serialize(research_row),
    }

    if file_path.exists():
        raise FileExistsError(
            f"Snapshot already exists: {file_path}"
        )

    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(
            snapshot,
            f,
            indent=4,
            sort_keys=True,
            default=str,
        )

    return {
        "recommendation_id": recommendation_id,
        "file_path": str(file_path),
        "created_utc": created_utc.isoformat(),
        "schema_version": SCHEMA_VERSION,
    }