"""
Project Stonks
Snapshot Writer

Sprint 33A

Purpose

Creates an immutable research snapshot for every completed observation
generated by Project Stonks.

The snapshot represents historical truth and must NEVER be modified after
it has been written.

Responsibilities

- Generate a Recommendation ID
- Build an immutable completed-observation snapshot
- Persist the snapshot to disk as JSON
- Return snapshot metadata to the caller

This module intentionally contains no trading business logic.
"""

from __future__ import annotations

import json
import uuid
from dataclasses import asdict, is_dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from data_quality import assess_observation


SCHEMA_VERSION = "4.0"
MODEL_VERSION = "0.3.0-alpha"

SNAPSHOT_DIRECTORY = (
    Path(__file__).resolve().parent.parent
    / "data"
    / "history"
    / "recommendations"
)


def _serialize(value: Any):
    """
    Recursively convert objects into JSON-safe values.
    """

    if is_dataclass(value):
        return _serialize(asdict(value))

    if isinstance(value, dict):
        return {
            str(key): _serialize(item)
            for key, item in value.items()
        }

    if isinstance(value, (list, tuple)):
        return [
            _serialize(item)
            for item in value
        ]

    if hasattr(value, "item"):
        try:
            return value.item()
        except Exception:
            pass

    if hasattr(value, "__dict__"):
        return _serialize(
            vars(value)
        )

    if isinstance(value, datetime):
        return value.isoformat()

    return value


def write_observation_snapshot(
    observation: dict,
) -> dict:
    """
    Write one immutable completed-observation snapshot.

    Parameters
    ----------
    observation
        Fully enriched observation dictionary containing the
        research, opportunity, option-selection, allocation,
        market, and version state that existed when the scan ran.

    Returns
    -------
    dict

    {
        "recommendation_id": "...",
        "file_path": "...",
        "created_utc": "...",
        "schema_version": "3.0"
    }
    """

    recommendation_id = str(
        uuid.uuid4()
    )

    created_utc = datetime.now(
        timezone.utc
    )

    SNAPSHOT_DIRECTORY.mkdir(
        parents=True,
        exist_ok=True,
    )

    timestamp = created_utc.strftime(
        "%Y%m%d_%H%M%S"
    )

    ticker = str(
        observation.get(
            "ticker",
            observation.get(
                "Ticker",
                "UNKNOWN",
            ),
        )
    ).upper().strip()

    filename = (
        f"{timestamp}_"
        f"{ticker}_"
        f"{recommendation_id}.json"
    )

    file_path = (
        SNAPSHOT_DIRECTORY
        / filename
    )

    assessed_observation = assess_observation(
        observation
    )

    snapshot = {
        "schema_version": SCHEMA_VERSION,
        "model_version": MODEL_VERSION,
        "recommendation_id": recommendation_id,
        "created_utc": created_utc.isoformat(),
        "data_quality_status": assessed_observation[
            "DataQualityStatus"
        ],
        "observation": _serialize(
            assessed_observation
        ),
    }

    if file_path.exists():
        raise FileExistsError(
            f"Snapshot already exists: "
            f"{file_path}"
        )

    with open(
        file_path,
        "w",
        encoding="utf-8",
    ) as file_handle:

        json.dump(
            snapshot,
            file_handle,
            indent=4,
            sort_keys=True,
            default=str,
        )

    return {
        "recommendation_id": (
            recommendation_id
        ),
        "file_path": str(
            file_path
        ),
        "created_utc": (
            created_utc.isoformat()
        ),
        "schema_version": (
            SCHEMA_VERSION
        ),
    }


def write_snapshot(
    trade,
    research_row,
):
    """
    Legacy compatibility wrapper.

    Existing callers can continue using write_snapshot()
    while the remaining pipeline is migrated.

    The wrapper combines the supplied research row and
    trade object into one observation before delegating
    to write_observation_snapshot().
    """

    observation = {}

    if isinstance(
        research_row,
        dict,
    ):
        observation.update(
            research_row
        )

    elif hasattr(
        research_row,
        "to_dict",
    ):
        observation.update(
            research_row.to_dict()
        )

    if trade is not None:

        if is_dataclass(
            trade
        ):
            trade_dict = asdict(
                trade
            )

        elif isinstance(
            trade,
            dict,
        ):
            trade_dict = dict(
                trade
            )

        elif hasattr(
            trade,
            "__dict__",
        ):
            trade_dict = dict(
                vars(trade)
            )

        else:
            trade_dict = {}

        for key, value in trade_dict.items():
            observation.setdefault(
                key,
                value,
            )

    return write_observation_snapshot(
        observation
    )
