"""
Project Stonks
Trade Journal

Sprint 32C

Immutable research journal.

This file records every recommendation generated by Project Stonks.
Portfolio state is maintained separately in paper_portfolio.csv.

Journal writes are atomic so an interrupted process cannot leave the
primary CSV partially written.
"""

from __future__ import annotations

import os
from dataclasses import asdict
from datetime import datetime
from pathlib import Path

import pandas as pd
import yfinance as yf

from config import (
    VERSION,
    CONFIG_VERSION,
    ENABLE_JOURNAL_WRITES,
)
from snapshot_writer import write_snapshot


PROJECT_ROOT = Path(__file__).resolve().parent.parent
JOURNAL_PATH = PROJECT_ROOT / "data" / "trade_journal.csv"


def _classify_trade_status(
    trade_dict: dict,
) -> str:

    if trade_dict.get("action") == "Watch":
        return "WATCHLIST"

    if trade_dict.get("action") != "Evaluate Options":
        return "PASS"

    if trade_dict.get("option_strategy") is None:
        return "NOT_EXECUTABLE"

    if trade_dict.get("contracts") in [None, 0]:
        return "NOT_EXECUTABLE"

    return "PAPER_TRADE_CANDIDATE"


def _get_latest_underlying_price(
    ticker: str,
):

    try:

        stock = yf.Ticker(ticker)

        history = stock.history(
            period="5d",
        )

        if history.empty:
            return None

        return float(
            history["Close"].iloc[-1]
        )

    except Exception:
        return None


def _load_existing_journal() -> pd.DataFrame:

    if not JOURNAL_PATH.exists():
        return pd.DataFrame()

    if JOURNAL_PATH.stat().st_size == 0:
        return pd.DataFrame()

    try:
        return pd.read_csv(JOURNAL_PATH)

    except pd.errors.ParserError as error:
        raise RuntimeError(
            "Trade journal is not readable. "
            "Run repair_trade_journal.py before generating "
            "additional recommendations."
        ) from error


def _write_journal_atomically(
    journal: pd.DataFrame,
):

    JOURNAL_PATH.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    temporary_path = JOURNAL_PATH.with_suffix(
        ".writing.csv"
    )

    try:

        journal.to_csv(
            temporary_path,
            index=False,
        )

        #
        # Validate before replacing
        #

        pd.read_csv(
            temporary_path
        )

        os.replace(
            temporary_path,
            JOURNAL_PATH,
        )

    finally:

        if temporary_path.exists():
            temporary_path.unlink()


def log_trade_recommendation(
    trade,
) -> None:

    #
    # Development mode
    #

    if not ENABLE_JOURNAL_WRITES:
        return

    timestamp = datetime.now()

    trade_dict = asdict(
        trade
    )

    #
    # Future-proof schema
    #

    trade_dict.setdefault(
        "ExecutionRecommendation",
        None,
    )

    trade_dict.setdefault(
        "InstitutionalTradeScore",
        None,
    )

    trade_dict.setdefault(
        "PortfolioScore",
        None,
    )

    trade_dict["RecommendationDate"] = (
        timestamp.isoformat(
            timespec="seconds",
        )
    )

    trade_dict["ProjectVersion"] = VERSION

    trade_dict["ConfigVersion"] = CONFIG_VERSION

    trade_dict["TradeStatus"] = (
        _classify_trade_status(
            trade_dict
        )
    )

    #
    # Immutable research context
    #

    trade_dict["EntryUnderlyingPrice"] = (
        _get_latest_underlying_price(
            trade_dict["ticker"]
        )
    )

    snapshot_info = write_snapshot(
        trade=trade,
        research_row=trade_dict,
    )

    trade_dict["RecommendationID"] = (
        snapshot_info["recommendation_id"]
    )

    trade_dict["SnapshotPath"] = (
        snapshot_info["file_path"]
    )

    trade_dict["SnapshotSchemaVersion"] = (
        snapshot_info["schema_version"]
    )

    #
    # Stable column ordering
    #

    priority_columns = [
        "RecommendationID",
        "RecommendationDate",
        "ticker",
        "action",
        "confidence",
        "TradeStatus",
        "trade_quality_score",
        "trade_quality_grade",
        "execution_score",
        "execution_grade",
        "execution_friction",
        "ExecutionRecommendation",
        "InstitutionalTradeScore",
        "PortfolioScore",
    ]

    remaining = [
        column
        for column in trade_dict.keys()
        if column not in priority_columns
    ]

    ordered = (
        priority_columns
        + remaining
    )

    trade_dict = {
        column: trade_dict.get(column)
        for column in ordered
    }

    new_row = pd.DataFrame(
        [trade_dict]
    )

    existing = _load_existing_journal()

    if existing.empty:

        updated_journal = new_row

    else:

        updated_journal = pd.concat(
            [
                existing,
                new_row,
            ],
            ignore_index=True,
            sort=False,
        )

    _write_journal_atomically(
        updated_journal
    )