"""
Project Stonks
Trade Journal

Sprint 32C

Immutable research journal.

This file records every recommendation generated by Project Stonks.
Portfolio state is maintained separately in paper_portfolio.csv.

Journal writes are atomic so an interrupted process cannot leave the
primary CSV partially written.

Batch mode allows a scan to prepare multiple journal entries in memory
and persist them with one atomic journal transaction.
"""

from __future__ import annotations

import os
from dataclasses import asdict
from datetime import datetime
from pathlib import Path

import pandas as pd

from schwab.market_data_client import (
    get_normalized_quote,
)

from config import (
    VERSION,
    CONFIG_VERSION,
    ENABLE_JOURNAL_WRITES,
)
from snapshot_writer import write_snapshot


PROJECT_ROOT = Path(__file__).resolve().parent.parent
JOURNAL_PATH = PROJECT_ROOT / "data" / "trade_journal.csv"


#
# Journal batch state
#
# The Opportunity Engine can continue calling
# log_trade_recommendation() exactly as before.
#
# When batch mode is active, prepared rows are held
# in memory until flush_journal_batch() is called.
#

_JOURNAL_BATCH_ACTIVE = False
_JOURNAL_BATCH_ROWS: list[dict] = []


def _classify_trade_status(
    trade_dict: dict,
) -> str:

    if trade_dict.get("action") == "Watch":
        return "WATCHLIST"

    if trade_dict.get("action") != "Evaluate Options":
        return "PASS"

    if trade_dict.get("option_strategy") is None:
        return "NOT_EXECUTABLE"

    if trade_dict.get("contracts") in [None, 0]:
        return "NOT_EXECUTABLE"

    return "PAPER_TRADE_CANDIDATE"


def _get_latest_underlying_price(
    ticker: str,
):
    """
    Retrieve the latest underlying price from
    Schwab Market Data.

    Pricing preference:

    1. Mark
    2. Last
    3. Bid/ask midpoint

    Returns None when no usable price is available.
    """

    try:

        quote = get_normalized_quote(
            ticker
        )

        mark = pd.to_numeric(
            quote.get("Mark"),
            errors="coerce",
        )

        if (
            pd.notna(mark)
            and float(mark) > 0
        ):
            return float(mark)

        last_price = pd.to_numeric(
            quote.get("Last"),
            errors="coerce",
        )

        if (
            pd.notna(last_price)
            and float(last_price) > 0
        ):
            return float(last_price)

        bid = pd.to_numeric(
            quote.get("Bid"),
            errors="coerce",
        )

        ask = pd.to_numeric(
            quote.get("Ask"),
            errors="coerce",
        )

        if (
            pd.notna(bid)
            and pd.notna(ask)
            and float(bid) > 0
            and float(ask) > 0
        ):
            return (
                float(bid)
                + float(ask)
            ) / 2

        return None

    except Exception:
        return None


def _load_existing_journal() -> pd.DataFrame:

    if not JOURNAL_PATH.exists():
        return pd.DataFrame()

    if JOURNAL_PATH.stat().st_size == 0:
        return pd.DataFrame()

    try:

        return pd.read_csv(
            JOURNAL_PATH,
            low_memory=False,
        )

    except pd.errors.ParserError as error:

        raise RuntimeError(
            "Trade journal is not readable. "
            "Run repair_trade_journal.py before generating "
            "additional recommendations."
        ) from error


def _write_journal_atomically(
    journal: pd.DataFrame,
):

    JOURNAL_PATH.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    temporary_path = JOURNAL_PATH.with_suffix(
        ".writing.csv"
    )

    try:

        journal.to_csv(
            temporary_path,
            index=False,
        )

        #
        # Validate the completed temporary file before
        # replacing the immutable journal.
        #

        pd.read_csv(
            temporary_path,
            low_memory=False,
        )

        os.replace(
            temporary_path,
            JOURNAL_PATH,
        )

    finally:

        if temporary_path.exists():
            temporary_path.unlink()


def _prepare_journal_row(
    trade,
) -> dict:
    """
    Convert one TradeRecommendation into its
    immutable journal representation.

    Snapshot creation remains here so the snapshot
    and journal row continue to share the same
    RecommendationID and research context.
    """

    timestamp = datetime.now()

    trade_dict = asdict(
        trade
    )

    #
    # Future-proof schema
    #

    trade_dict.setdefault(
        "ExecutionRecommendation",
        None,
    )

    trade_dict.setdefault(
        "InstitutionalTradeScore",
        None,
    )

    trade_dict.setdefault(
        "PortfolioScore",
        None,
    )

    trade_dict["RecommendationDate"] = (
        timestamp.isoformat(
            timespec="seconds",
        )
    )

    trade_dict["ProjectVersion"] = VERSION

    trade_dict["ConfigVersion"] = CONFIG_VERSION

    trade_dict["TradeStatus"] = (
        _classify_trade_status(
            trade_dict
        )
    )

    #
    # Immutable research context
    #

    trade_dict["EntryUnderlyingPrice"] = (
        _get_latest_underlying_price(
            trade_dict["ticker"]
        )
    )

    snapshot_info = write_snapshot(
        trade=trade,
        research_row=trade_dict,
    )

    trade_dict["RecommendationID"] = (
        snapshot_info["recommendation_id"]
    )

    trade_dict["SnapshotPath"] = (
        snapshot_info["file_path"]
    )

    trade_dict["SnapshotSchemaVersion"] = (
        snapshot_info["schema_version"]
    )

    #
    # Stable column ordering
    #

    priority_columns = [
        "RecommendationID",
        "RecommendationDate",
        "ticker",
        "action",
        "confidence",
        "TradeStatus",
        "trade_quality_score",
        "trade_quality_grade",
        "execution_score",
        "execution_grade",
        "execution_friction",
        "ExecutionRecommendation",
        "InstitutionalTradeScore",
        "PortfolioScore",
    ]

    remaining = [
        column
        for column in trade_dict.keys()
        if column not in priority_columns
    ]

    ordered = (
        priority_columns
        + remaining
    )

    return {
        column: trade_dict.get(column)
        for column in ordered
    }


def _append_rows_to_journal(
    rows: list[dict],
) -> None:
    """
    Append prepared journal rows using one atomic
    read / concatenate / write transaction.
    """

    if not rows:
        return

    new_rows = pd.DataFrame(
        rows
    )

    existing = _load_existing_journal()

    if existing.empty:

        updated_journal = new_rows

    else:

        updated_journal = pd.concat(
            [
                existing,
                new_rows,
            ],
            ignore_index=True,
            sort=False,
        )

    _write_journal_atomically(
        updated_journal
    )


def begin_journal_batch() -> None:
    """
    Begin buffering journal rows in memory.

    Existing buffered state is cleared intentionally
    so every scan starts with a clean batch.
    """

    global _JOURNAL_BATCH_ACTIVE
    global _JOURNAL_BATCH_ROWS

    _JOURNAL_BATCH_ROWS = []
    _JOURNAL_BATCH_ACTIVE = True


def flush_journal_batch() -> int:
    """
    Persist all buffered journal rows with one atomic
    journal transaction.

    Returns the number of rows written.
    """

    global _JOURNAL_BATCH_ACTIVE
    global _JOURNAL_BATCH_ROWS

    rows_to_write = list(
        _JOURNAL_BATCH_ROWS
    )

    row_count = len(
        rows_to_write
    )

    try:

        if (
            ENABLE_JOURNAL_WRITES
            and rows_to_write
        ):

            _append_rows_to_journal(
                rows_to_write
            )

    except Exception:

        #
        # Preserve the buffered rows if persistence
        # fails so state is not silently discarded.
        #

        _JOURNAL_BATCH_ROWS = rows_to_write

        raise

    else:

        _JOURNAL_BATCH_ROWS = []
        _JOURNAL_BATCH_ACTIVE = False

    return row_count


def cancel_journal_batch() -> int:
    """
    Discard buffered journal rows without writing them.

    Snapshots already created during preparation remain
    immutable artifacts and are not deleted.

    Returns the number of buffered rows discarded.
    """

    global _JOURNAL_BATCH_ACTIVE
    global _JOURNAL_BATCH_ROWS

    row_count = len(
        _JOURNAL_BATCH_ROWS
    )

    _JOURNAL_BATCH_ROWS = []
    _JOURNAL_BATCH_ACTIVE = False

    return row_count


def log_trade_recommendation(
    trade,
) -> None:
    """
    Record one trade recommendation.

    Normal mode:
        Persist immediately using an atomic journal
        transaction.

    Batch mode:
        Prepare the immutable row and snapshot, then
        buffer the row until flush_journal_batch().
    """

    if not ENABLE_JOURNAL_WRITES:
        return

    journal_row = _prepare_journal_row(
        trade
    )

    if _JOURNAL_BATCH_ACTIVE:

        _JOURNAL_BATCH_ROWS.append(
            journal_row
        )

        return

    #
    # Backward-compatible immediate-write behavior.
    #

    _append_rows_to_journal(
        [journal_row]
    )